model:
  name: ResNet32
  architecture:
    in_channels: 3
    out_channels: 10
    activation: HELU

optimizer:
  name: SGD
  parameters:
    lr: 0.1
    weight_decay: 0.0001
    momentum: 0.9

scheduler:
  num: 1
  scheduler0:
    name: MultiStepLR
    parameters:
      milestones: [45, 65]
      gamma: 0.1

dataset:
  name: CIFAR10
  batch_size: 128
  split:
    train: 0.9
    valid: 0.1
    test: 1.0

train:
  epochs: 90
  device: cuda:0
  save_path: ./checkpoints/helu/cifar10/
  log_path: ./logs/helu/cifar10/
  seed: 42
  save_every: 10

test:
  device: cuda:0
  checkpoint: ./checkpoints/helu/cifar10/
  log_path: ./logs/helu/cifar10/
  seed: 42
